TARGET  = fluidanimate
SRC     = openmp.cpp 
CSRC    = $(SRC)

CXX += -fopenmp

all: openmp cmp

openmp: $(CSRC)
	$(CXX) $(CXXFLAGS) $(CSRC) $(LDFLAGS) $(LIBS) -o $(TARGET)

cmp: cmp.cpp
	rm -rf cmp
	$(CXX) cmp.cpp -o cmp
clean:
	rm -rf $(TARGET) 
	rm -rf cmp
